./../example_design/bench/ddr_test_top_tb.v                                 
./../example_design/bench/mem/ddr3.v                                        
./../example_design/bench/mem/ddr3_parameters.vh                            
                                                                            
./../example_design/rtl/test_rd_ctrl_128bit.v                               
./../example_design/rtl/test_wr_ctrl_128bit.v                               
./../example_design/rtl/test_rd_ctrl_64bit.v                                
./../example_design/rtl/test_wr_ctrl_64bit.v                                
./../example_design/rtl/ipsl_hmic_h_top_test.v                                
./../example_design/rtl/test_main_ctrl.v                                    
./../example_design/rtl/prbs31_128bit.v                                     
                                                                            
./../rtl/pll/pll_50_400_v1_1.v                                                   
./../rtl/ipsl_hmic_h_ddrc_apb_reset_v1_1.v                                                   
./../rtl/ipsl_hmic_h_ddrc_reset_ctrl_v1_1.v                                              
./../rtl/ipsl_hmic_h_ddrphy_dll_update_ctrl_v1_1.v                                       
./../rtl/ipsl_hmic_h_ddrphy_reset_ctrl_v1_1.v                                            
./../rtl/ipsl_hmic_h_ddrphy_training_ctrl_v1_1.v                                         
./../rtl/ipsl_hmic_h_ddrphy_update_ctrl_v1_1.v                                           
./../rtl/ipsl_hmic_h_ddrc_top_v1_1.v                                               
./../rtl/ipsl_hmic_h_phy_top_v1_1.v                                                
./../rtl/ipsl_hmic_h_phy_io_v1_1.v                                                       
./../ddr3_core.v                                                            
                                                                            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/rstn_sync.vp                       
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/sync.vp                                           
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/sync_h.vp                                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/sadrlspk42p32x64m1b1w0c0p0d0t0_fast_func.vp       
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/sadrlspk42p32x64m1b1w0c0p0d0t0read_fast_func.vp   
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/DWC_ddr_umctl2_cc_constants.vp               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ddrc_parameters.vp                           
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_apb_defines.vp            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/DWC_ddr_umctl2.vp                            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_retime.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm21.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm05.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm07.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm02.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm06.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm50.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm56.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm_wrap_mem_array.vp     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm57.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_bcm65.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/rt/DWC_ddr_umctl2_gfifo.vp                   
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_mux.vp                                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/be/bypass.vp                                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/rd/rd.vp                                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_core_in_if.vp                          
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_core_out_if.vp                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_address_map.vp                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_address_map_wrapper.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_be_if.vp                               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_te_if.vp                               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_fifo_if.vp                             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_fifo_control.vp                        
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih.vp                                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/mr/mr_data_steering.vp                       
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/mr/mr_ram_rd_pipeline.vp                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/mr/mr.vp                                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pi/pi.vp                                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/rt/rt.vp                                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/select_nets/select_node.vp                   
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/select_nets/select_net.vp                    
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/select_nets/select_node_lite.vp              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/select_nets/select_net_lite.vp               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_nxt_vp_update.vp                       
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_filter_vp.vp                           
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_filter.vp                              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_rd_nxt.vp                              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_wr_nxt.vp                              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_rd_replace.vp                          
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_wr_replace.vp                          
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_rd_cam.vp                              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_rd_entry.vp                            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_rd_mux.vp                              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/teengine.vp                               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_wr_cam.vp                              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_wr_entry.vp                            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_wr_mux.vp                              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_misc.vp                                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/bsm.vp                                    
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_phyupd.vp                              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_phymstr.vp                             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_ctrlupd.vp                             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_zq_calib.vp                            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_global_constraints.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_global_fsm.vp                          
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_global_fsm_sr_hw_lp.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_dfilp.vp                               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_q_fsm.vp                               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_glue.vp                                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_init_ddr_fsm.vp                        
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_next_xact.vp                           
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_rank_constraints.vp                    
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_odt.vp                                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs.vp                                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_load_mr.vp                             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_ref_rdwr_switch.vp                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/os_glue.vp                                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/ts.vp                                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/wu/memc_wu.vp                                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/wu/memc_wu_wdata_if.vp                       
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/fifo/sync_fifo_rst.vp                        
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/fifo/ingot_sync_fifo_flopout_rst.vp          
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/dfi/wrdata_no_toggle.vp                      
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/dfi/dfi.vp                                   
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/top/ddrc.vp                                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/top/ddrc_assertions.svp                      
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ih/ih_assertions.svp                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pi/pi_assertions.svp                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/te/te_assertions.svp                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/gs_assertions.svp                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/ts/ts_assertions.svp                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/field_packer9.vp                         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/field_packer10.vp                        
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/field_packer12.vp                        
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/field_packer13.vp                        
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_assomem.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/async_fifo_checker.vp                    
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/sync_fifo_checker.vp                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_gafifo.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_gafifo_split.vp           
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_grfifo.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_retime_a.vp               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_dcm.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_tm.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_rrb.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_lpfsm.vp              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_ws.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_rp.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_wp.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_dg.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_df.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_ad.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_wdd.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_rdu.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_rd_q.vp               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_qos.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_vpt.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_write.vp              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_read.vp               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi.vp                    
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/xpi/DWC_ddr_umctl2_xpi_and.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_bcm25.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_bcm23.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_rstn_sync.vp              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_wr_en_sync.vp             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_reg_en.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_bitsync.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_datasync.vp               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_onetoset.vp               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_static_ff.vp              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_apb_coreif.vp             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_apb_adrdec.vp             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_apb_slvif.vp              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_apb_slvfsm.vp             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/apb/DWC_ddr_umctl2_apb_slvtop.vp             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_pa_roundrobincore.vp       
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_pa_arb.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_pa_priocomp.vp             
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_pa_preproc.vp              
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_pa_port.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_pa.vp                      
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_pa_dual.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_hif_cmd.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_hif_data.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/pa/DWC_ddr_umctl2_pm_mask.vp                 
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_source_codes/ddrc/DWC_ddr_umctl2-undef.vp                      
                                                                            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_gtp_wrap.vp                                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrc_gtp_wrap.vp                                    
                                                                            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_apb.vp                      
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_calib_mux.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_calib_top.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_control_path_adj.vp         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_data_slice_dqs_gate_cal.vp  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_data_slice.vp               
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_data_slice_wrlvl.vp         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_dfi.vp                      
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_dqs_gate_coarse_cal.vp      
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_dqs_gate_fine_cal.vp        
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_dqsi_rdel_cal.vp            
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_dqs_rddata_align.vp         
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_info.vp                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_init.vp                     
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_main_ctrl.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_rdcal.vp                    
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_slice_rddata_align.vp       
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_slice_top.vp                
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_wdata_path_adj.vp           
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_wrlvl.vp                    
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_update.vp                   
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_rowaddr.vp                  
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_top.vp                      
/opt/pds/pango/PDS_2020.2/ip/system_ip/ipsl_hmic_h/ipsl_hmic_h_eval/ipsl_hmic_h/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddrphy_source_codes/ddrphy/pgl_ddrphy_gatecal.vp                  
                                                                     
+define+SIMULATION  
+define+den4096Mb   
+define+sg25E       
+define+x16         
