## Generated by Fabric Configuration (version 2021.1-SP7.3 build 94852) at Tue Oct  4 22:12:45 2022
cfg_connect -ip 127.0.0.1 -port 65420

cfg_add_device -file generate_bitstream/tcl_bit_file/%top%Wrapper.sbit
cfg_program -device_index 0
# cfg_verify -device_index 0
exit